import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
            public class adminviewstock extends javax.swing.JFrame {
                Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
                /** Creates new form ${name} */
                public adminviewstock(String text) {
                    initComponents();
                    conn=javaconnect.ConnecrDb();
                    fillcombo();
                     fillcombo1();
                  userid.setText(text);
                  userid.setVisible(false);
                     setTitle("WELCOME TO STOCK DETAILS PAGE");
                }

    private adminviewstock() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
                 public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
                
                /** This method is called from within the constructor to
                 * initialize the form.
                 * WARNING: Do NOT modify this code. The content of this method is
                 * always regenerated by the Form Editor.
                 */
                @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemname = new javax.swing.JComboBox();
        branch = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewstock = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        userid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        itemname.setForeground(new java.awt.Color(0, 0, 204));

        branch.setForeground(new java.awt.Color(0, 0, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        viewstock.setForeground(new java.awt.Color(0, 0, 204));
        viewstock.setText("VIEW STOCK");
        viewstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstockActionPerformed(evt);
            }
        });

        logout.setForeground(new java.awt.Color(204, 0, 153));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        back.setForeground(new java.awt.Color(204, 0, 204));
        back.setText("< BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(branch, javax.swing.GroupLayout.Alignment.LEADING, 0, 105, Short.MAX_VALUE)
                                        .addComponent(itemname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(viewstock)))
                            .addGap(159, 159, 159))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(back)
                            .addGap(106, 106, 106)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(703, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout)
                            .addComponent(back))
                        .addGap(43, 43, 43)
                        .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(viewstock)
                        .addGap(89, 89, 89)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                private void viewstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstockActionPerformed
                    try {
                        Object item =itemname.getSelectedItem();
                        Object item1 =branch.getSelectedItem();
                        String sql3="SELECT itemname,COUNT(itemid) AS presentstock FROM stock WHERE branch='"+item1+"' and itemname='"+item+"'";

                        pst = conn.prepareStatement(sql3);



                        rs=pst.executeQuery();


                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null,e );

                    }
                }//GEN-LAST:event_viewstockActionPerformed

                private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
                    close();
                    login s=new login();
                    s.setVisible(true);
}//GEN-LAST:event_logoutActionPerformed

                private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                       close();
                    adminviewdb s=new adminviewdb(this.userid.getText());
                    s.setVisible(true);
                }//GEN-LAST:event_backActionPerformed
                
                /**
                 * @param args the command line arguments
                 */ private void fillcombo(){
    try{
        String sql="select * from branch";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String name=rs.getString("branchname");
           branch.addItem(name);
        }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
                }
                private void fillcombo1(){
    try{
        String sql="select DISTINCT itemname from stock";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String name=rs.getString("itemname");
           itemname.addItem(name);
        }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
                }
                public static void main(String args[]) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new adminviewstock().setVisible(true);
                        }
                    });
                }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox branch;
    private javax.swing.JComboBox itemname;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField userid;
    private javax.swing.JButton viewstock;
    // End of variables declaration//GEN-END:variables
                
            }
