


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Event.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeListener;
public class admin extends javax.swing.JFrame {
Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
    
    public admin(String text) {
        initComponents();
       

       userid.setText(text);
      
       
       
         conn=javaconnect.ConnecrDb();
         setTitle("WELCOME TO ADMIN PAGE");
    }

    public admin() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    
   

    
     public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmd_createnewsupervisor = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userid = new javax.swing.JLabel();
        addbranch = new javax.swing.JButton();
        vdb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24));
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("WELCOME TO ADMINISTRATOR :");

        cmd_createnewsupervisor.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmd_createnewsupervisor.setForeground(new java.awt.Color(255, 51, 102));
        cmd_createnewsupervisor.setText("CURD OPERATION FOR USER");
        cmd_createnewsupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_createnewsupervisorActionPerformed(evt);
            }
        });

        logout.setForeground(new java.awt.Color(255, 102, 102));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));

        userid.setFont(new java.awt.Font("Agency FB", 1, 36));
        userid.setForeground(new java.awt.Color(0, 0, 255));
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridKeyReleased(evt);
            }
        });

        addbranch.setFont(new java.awt.Font("Tahoma", 0, 14));
        addbranch.setForeground(new java.awt.Color(255, 0, 51));
        addbranch.setText("ADD NEW BRANCH");
        addbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbranchActionPerformed(evt);
            }
        });

        vdb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vdb.setForeground(new java.awt.Color(204, 0, 0));
        vdb.setText("VIEW DATABASE");
        vdb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(vdb, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cmd_createnewsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(addbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_createnewsupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vdb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(addbranch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void formPropertyChange(java.beans.PropertyChangeEvent evt) {
         if (evt.getPropertyName().equals("textchange")){
           userid.setText((String)evt.getNewValue());

    }
    }

    private void cmd_createnewsupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_createnewsupervisorActionPerformed
close();
        saveemployee s=new saveemployee(this.userid.getText());
s.setVisible(true);
 this.addPropertyChangeListener((PropertyChangeListener) s);
    }//GEN-LAST:event_cmd_createnewsupervisorActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

                close();
                    login s=new login();
                    s.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyReleased
         firePropertyChange("textchange", "", userid.getText());
    }//GEN-LAST:event_useridKeyReleased

    private void addbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbranchActionPerformed
     close();
        newbranch s=new newbranch(this.userid.getText());
     s.setVisible(true);
     this.addPropertyChangeListener((PropertyChangeListener) s);
    }//GEN-LAST:event_addbranchActionPerformed

    private void vdbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdbActionPerformed
       close();
        adminviewdb bjf = new adminviewdb(this.userid.getText());
        bjf.setVisible(true);
         this.addPropertyChangeListener((PropertyChangeListener) bjf);
    }//GEN-LAST:event_vdbActionPerformed

    

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbranch;
    private javax.swing.JButton cmd_createnewsupervisor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logout;
    private javax.swing.JLabel userid;
    private javax.swing.JButton vdb;
    // End of variables declaration//GEN-END:variables

}
