/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on May 25, 2012, 2:47:52 PM
 */

/**
 *
 * @author PAVAN
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import java.awt.Event.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeListener;
public class login extends javax.swing.JFrame {
 Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
    /** Creates new form login */
    public login() {
        initComponents();
        conn=javaconnect.ConnecrDb();
        fillcombo();
        fillcombo1();
         setTitle("WELCOME TO PAVAN STORES");
    }
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
private void fillcombo(){
    try{
        String sql="select * from branch";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String name=rs.getString("branchname");
           ComboBox_branch.addItem(name);
        }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }






    }
private void fillcombo1(){
    try{
        String sql="select DISTINCT role from employeeinfo";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            String name=rs.getString("role");
          ComboBox_role.addItem(name);
        }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
                }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_branch = new javax.swing.JComboBox();
        ComboBox_role = new javax.swing.JComboBox();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PasswordField1 = new javax.swing.JPasswordField();
        forget = new javax.swing.JButton();
        change = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("USER ID");

        userid.setForeground(new java.awt.Color(204, 204, 204));
        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("PASSWORD");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24));
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("WELCOME TO PAVAN STORES");

        ComboBox_branch.setForeground(new java.awt.Color(51, 51, 255));
        ComboBox_branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_branchActionPerformed(evt);
            }
        });

        ComboBox_role.setForeground(new java.awt.Color(204, 204, 255));

        login.setFont(new java.awt.Font("Tahoma", 0, 14));
        login.setForeground(new java.awt.Color(51, 51, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("ROLE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("BRANCH");

        PasswordField1.setForeground(new java.awt.Color(255, 153, 255));

        forget.setText("forgetpassword");
        forget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetActionPerformed(evt);
            }
        });

        change.setText("change password");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(forget, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                        .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBox_branch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBox_role, 0, 120, Short.MAX_VALUE))))
                                .addGap(48, 48, 48)))
                        .addGap(120, 120, 120))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboBox_role, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBox_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forget)
                            .addComponent(change)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(login)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       Object item =ComboBox_role.getSelectedItem();
        Object item1 =ComboBox_branch.getSelectedItem();
        String sql="select * from employeeinfo where userid=? and password=? and role='"+item+"' and branch='"+item1+"'";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,userid.getText());
            pst.setString(2,PasswordField1.getText());


            rs=pst.executeQuery();
            while(rs.next()){
                
                      if((ComboBox_role.getSelectedItem().equals("administrator"))&&(ComboBox_branch.getSelectedItem().toString()!=null))
                {

                rs.close();
                pst.close();
                close();
                    admin s=new admin(this.userid.getText());
                    s.setVisible(true);
                    this.addPropertyChangeListener((PropertyChangeListener) s);
                            
                     
                  

                }

                else if ( (ComboBox_role.getSelectedItem().equals("supervisor"))&& (ComboBox_branch.getSelectedItem().toString()!=null)) {

                  rs.close();
                pst.close();
                close();
                    

                    supervisor m=new supervisor(this.userid.getText(),this.ComboBox_branch.getSelectedItem().toString());
                    m.setVisible(true);
     this.addPropertyChangeListener((PropertyChangeListener) m);
                }

                else if ( (ComboBox_role.getSelectedItem().equals("worker"))&&(ComboBox_branch.getSelectedItem().toString()!=null)) {
                     rs.close();
                pst.close();
                close();
                    worker w=new worker(this.userid.getText(),this.ComboBox_branch.getSelectedItem().toString());
                    w.setVisible(true);
                    this.addPropertyChangeListener((PropertyChangeListener) w);

                }
               else{
                    JOptionPane.showMessageDialog(null, "Username and Password is not correct" );
                }
            }
        } catch (Exception e){
           

        }finally{
            try{
                rs.close();
                pst.close();

            } catch(Exception e){
            }
}
    }//GEN-LAST:event_loginActionPerformed

    private void useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyReleased

       firePropertyChange("textchange", "", userid.getText());
    }//GEN-LAST:event_useridKeyReleased

    private void ComboBox_branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_branchActionPerformed

    private void forgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetActionPerformed
close();
forget s=new forget();
s.setVisible(true);
    }//GEN-LAST:event_forgetActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
close();
        changepass s=new changepass();
        s.setVisible(true);
    }//GEN-LAST:event_changeActionPerformed
 

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_branch;
    private javax.swing.JComboBox ComboBox_role;
    private javax.swing.JPasswordField PasswordField1;
    private javax.swing.JButton change;
    private javax.swing.JButton forget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables

}
