import java.awt.Toolkit;
import java.awt.event.WindowEvent;
 import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
            public class superamountcal extends javax.swing.JFrame {
                 Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
                /** Creates new form ${name} */
                public superamountcal(String text, String text1) {
                    initComponents();
                    conn=javaconnect.ConnecrDb();
                     Update_table();
                    branch.setText(text1);
                    branch.setVisible(false);
                     userid.setText(text);
                       userid.setVisible(false);
                       setTitle("WELCOME TO INDIVIDUAL WORKER MONEY TRANSACTION PAGE");
                }

    private superamountcal() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
                 private void Update_table()
    {
    try{
    String sql="SELECT * FROM trans where userid=?   order by date asc ";
    pst=conn.prepareStatement(sql);
     pst.setString(1,branch.getText());


    rs=pst.executeQuery( );
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
    }
}
                  private void formPropertyChange(java.beans.PropertyChangeEvent evt) {
         if (evt.getPropertyName().equals("textchange")){
            branch.setText((String)evt.getNewValue());
                     }
                }
                  public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
                /** This method is called from within the constructor to
                 * initialize the form.
                 * WARNING: Do NOT modify this code. The content of this method is
                 * always regenerated by the Form Editor.
                 */
                @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date = new javax.swing.JTextField();
        day = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewdaytotal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        date1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        date2 = new javax.swing.JTextField();
        between = new javax.swing.JButton();
        viewallamount = new javax.swing.JButton();
        viewalllll = new javax.swing.JButton();
        branch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userid = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DAY TRANSACTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        date.setForeground(new java.awt.Color(102, 102, 102));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        day.setForeground(new java.awt.Color(153, 0, 153));
        day.setText("View Individual Worker Amount");
        day.setFocusable(false);
        day.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        day.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("date");

        viewdaytotal.setForeground(new java.awt.Color(204, 0, 153));
        viewdaytotal.setText("View Total Amount");
        viewdaytotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdaytotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(viewdaytotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(viewdaytotal)
                .addGap(31, 31, 31)
                .addComponent(day)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALL TRANSACTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        date1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("date:");

        jLabel2.setText("TO");

        date2.setForeground(new java.awt.Color(102, 102, 102));

        between.setForeground(new java.awt.Color(153, 0, 153));
        between.setText("View Individual Worker Amount");
        between.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betweenActionPerformed(evt);
            }
        });

        viewallamount.setForeground(new java.awt.Color(204, 0, 204));
        viewallamount.setText("View Total Amount");
        viewallamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallamountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(viewallamount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(between)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addComponent(viewallamount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(between)
                .addContainerGap())
        );

        viewalllll.setForeground(new java.awt.Color(153, 0, 153));
        viewalllll.setText("VIEW ALL");
        viewalllll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewalllllActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        logout.setForeground(new java.awt.Color(153, 0, 153));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        back.setForeground(new java.awt.Color(153, 0, 153));
        back.setText("< BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(viewalllll, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1204, 1204, 1204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(viewalllll)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

                private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
                    // TODO add your handling code here:
}//GEN-LAST:event_dateActionPerformed

                private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
                    try {

                        String sql3="SELECT date,userid,SUM(cost) AS TotalAmountReceived FROM trans WHERE date=? and branch=? GROUP BY userid,date";

                        pst = conn.prepareStatement(sql3);
                        pst.setString(1,date.getText());
                        pst.setString(2,branch.getText());

                        rs=pst.executeQuery();


                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null,e );

                    }
}//GEN-LAST:event_dayActionPerformed

                private void betweenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betweenActionPerformed
                    Object item =date1.getText();
                    Object item1 =date2.getText();
                    String sql="select date,userid,SUM(cost)  AS TotalAmountReceived from trans where branch=? and date between '"+item+"' and '"+item1+"'GROUP BY userid,date order by date";
                    try{
                        pst=conn.prepareStatement(sql);
                        pst.setString(1,branch.getText());



                        rs=pst.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(Exception e) {
                        JOptionPane.showMessageDialog(null,e );
                    }
}//GEN-LAST:event_betweenActionPerformed

                private void viewalllllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewalllllActionPerformed
                    try {

                        String sql3="SELECT date,SUM(cost) AS TotalAmountReceived FROM trans WHERE branch=? GROUP BY date order by date asc";

                        pst = conn.prepareStatement(sql3);
                        pst.setString(1,branch.getText());

                        rs=pst.executeQuery();


                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null,e );

                    }
}//GEN-LAST:event_viewalllllActionPerformed

                private void viewdaytotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdaytotalActionPerformed
                 try {

                        String sql3="SELECT date,SUM(cost) AS TotalAmountReceived FROM trans WHERE date=? and branch=? GROUP BY date";

                        pst = conn.prepareStatement(sql3);
                        pst.setString(1,date.getText());
                        pst.setString(2,branch.getText());

                        rs=pst.executeQuery();


                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch(Exception e){
                        JOptionPane.showMessageDialog(null,e );

                    }
                }//GEN-LAST:event_viewdaytotalActionPerformed

                private void viewallamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallamountActionPerformed
                     Object item =date1.getText();
                    Object item1 =date2.getText();
                    String sql="select date,SUM(cost)  AS TotalAmountReceived from trans where branch=? and date between '"+item+"' and '"+item1+"'GROUP BY date order by date";
                    try{
                        pst=conn.prepareStatement(sql);
                        pst.setString(1,branch.getText());



                        rs=pst.executeQuery();

                        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                    }catch(Exception e) {
                        JOptionPane.showMessageDialog(null,e );
                    }
                }//GEN-LAST:event_viewallamountActionPerformed

                private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
                    close();
                    login s=new login();
                    s.setVisible(true);
}//GEN-LAST:event_logoutActionPerformed

                private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                   close();
                    supertransview s=new supertransview(this.userid.getText(),this.branch.getText());
                   s.setVisible(true);
                }//GEN-LAST:event_backActionPerformed
                
                /**
                 * @param args the command line arguments
                 */
                public static void main(String args[]) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new superamountcal().setVisible(true);
                        }
                    });
                }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton between;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField date2;
    private javax.swing.JButton day;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField userid;
    private javax.swing.JButton viewallamount;
    private javax.swing.JButton viewalllll;
    private javax.swing.JButton viewdaytotal;
    // End of variables declaration//GEN-END:variables
                
            }
