
    import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.Event.*;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JOptionPane;
            public class workertransconfirm extends javax.swing.JFrame {
                
              Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
                public workertransconfirm(String text, String text1) {
                     
                    initComponents();
                     conn=javaconnect.ConnecrDb();
                    userid.setText(text);
                    branch1.setText(text1);
                  userid.setEditable(false);
                  userid.setVisible(false);
                      itemname.setVisible(false);
                       cost.setVisible(false);
                        role.setVisible(false);
                         branch.setVisible(false);
                          branch1.setVisible(false);
                          setTitle("WELCOME TO TRANSACTION CONFIRMATION PAGE");
                }

    public workertransconfirm() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
                  private void formPropertyChange(java.beans.PropertyChangeEvent evt) {
         if (evt.getPropertyName().equals("textchange")){
            userid.setText((String)evt.getNewValue());
            itemid.setText((String)evt.getNewValue());
                      }
                }

                /** This method is called from within the constructor to
                 * initialize the form.
                 * WARNING: Do NOT modify this code. The content of this method is
                 * always regenerated by the Form Editor.
                 */
                @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        itemid = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        itemname = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        branch = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        branch1 = new javax.swing.JTextField();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("itemid");

        userid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                useridKeyReleased(evt);
            }
        });

        itemid.setForeground(new java.awt.Color(102, 102, 102));
        itemid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemidKeyReleased(evt);
            }
        });

        next.setForeground(new java.awt.Color(153, 0, 153));
        next.setText("NEXT >");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        itemname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemnameKeyReleased(evt);
            }
        });

        cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costActionPerformed(evt);
            }
        });

        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchActionPerformed(evt);
            }
        });

        back.setForeground(new java.awt.Color(153, 0, 153));
        back.setText("< BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        logout.setForeground(new java.awt.Color(153, 0, 153));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(branch, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(role, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(userid, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(cost, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(itemname, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(itemid, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(branch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
                private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

                    String sql="select * from stock where itemid=? ";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,itemid.getText());



            rs=pst.executeQuery();

            while(rs.next()){
                 String name=rs.getString("itemname");
           itemname.setText(name);
           itemname.setEditable(false);

           String name1=rs.getString("cost");
           cost.setText(name1);
           cost.setEditable(false);
               rs.close();
               pst.close();
                String sql1="select * from employeeinfo where userid=?";
        pst=conn.prepareStatement(sql1);
         pst.setString(1,userid.getText());
        rs=pst.executeQuery();
        while(rs.next()){
            String name3=rs.getString("role");
           role.setText(name3);
           role.setEditable(false);
           String name4=rs.getString("branch");
          branch.setText(name4);
          branch.setEditable(false);
        }

                     rs.close();
                pst.close();
                close();
               
               maketransworker s=new maketransworker(this.itemid.getText(),this.itemname.getText(),this.cost.getText(),this.userid.getText(),this.role.getText(),this.branch.getText());

                       s.setVisible(true);
                    this.addPropertyChangeListener((PropertyChangeListener) s);

                     }
           



                    }catch(Exception e){

                    }

                }//GEN-LAST:event_nextActionPerformed

                private void useridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_useridKeyReleased
                  firePropertyChange("textchange", "", userid.getText());
                }//GEN-LAST:event_useridKeyReleased

                private void itemidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemidKeyReleased
                    firePropertyChange("textchange", "",itemid.getText());
                }//GEN-LAST:event_itemidKeyReleased

                private void itemnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemnameKeyReleased
                    firePropertyChange("textchange", "",itemname.getText());
                }//GEN-LAST:event_itemnameKeyReleased

                private void costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costActionPerformed
                   firePropertyChange("textchange", "",cost.getText());
                }//GEN-LAST:event_costActionPerformed

                private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
                  firePropertyChange("textchange", "",role.getText());
                }//GEN-LAST:event_roleActionPerformed

                private void branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchActionPerformed
                    firePropertyChange("textchange", "",branch.getText());
                }//GEN-LAST:event_branchActionPerformed

                private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
                    close();
                    worker s= new worker(this.userid.getText(),this.branch1.getText());
                    s.setVisible(true);
                }//GEN-LAST:event_backActionPerformed

                private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
                    close();
                    login s=new login();
                    s.setVisible(true);
}//GEN-LAST:event_logoutActionPerformed
                
                /**
                 * @param args the command line arguments
                 */
                public static void main(String args[]) {
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new workertransconfirm().setVisible(true);
                        }
                    });
                }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField branch;
    private javax.swing.JTextField branch1;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextField itemname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton next;
    private javax.swing.JTextField role;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
                
            }
