/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * worker.java
 *
 * Created on May 20, 2012, 7:31:12 PM
 */

/**
 *
 * @author PAVAN
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import java.awt.Event.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeListener;
public class worker extends javax.swing.JFrame {
Connection conn=null;
     ResultSet rs=null;
     PreparedStatement pst=null;
    /** Creates new form worker */
    public worker(String text, String tostring ) {
        initComponents();
       jLabel2.setText(text);
       branch.setText(tostring);
      
       
       
      
       
       conn=javaconnect.ConnecrDb();
       setTitle("WELCOME TO WORKER PAGE");
     
      
        
        
       

    }

    public worker() {
        
       
        
        throw new UnsupportedOperationException("Not yet implemented");
    }

    worker(String text, String toString, String toString0) {
        throw new UnsupportedOperationException("Not yet implemented");
    }
   

 private void formPropertyChange(java.beans.PropertyChangeEvent evt) {
         if (evt.getPropertyName().equals("textchange")){
            jLabel2.setText((String)evt.getNewValue());

    }
    }
  public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
      Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmd_maketransaction = new javax.swing.JButton();
        cmd_addstock = new javax.swing.JButton();
        cmd_viewalltransactions = new javax.swing.JButton();
        cmd_viewstockadded = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 36));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("WELCOME TO WORKER:");

        cmd_maketransaction.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmd_maketransaction.setForeground(new java.awt.Color(255, 102, 102));
        cmd_maketransaction.setText("MAKE TRANSACTION");
        cmd_maketransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_maketransactionActionPerformed(evt);
            }
        });

        cmd_addstock.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmd_addstock.setForeground(new java.awt.Color(255, 51, 51));
        cmd_addstock.setText("ADD STOCK");
        cmd_addstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addstockActionPerformed(evt);
            }
        });

        cmd_viewalltransactions.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmd_viewalltransactions.setForeground(new java.awt.Color(255, 102, 102));
        cmd_viewalltransactions.setText("VIEW ALL TRANSACTIONS");
        cmd_viewalltransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_viewalltransactionsActionPerformed(evt);
            }
        });

        cmd_viewstockadded.setFont(new java.awt.Font("Tahoma", 0, 14));
        cmd_viewstockadded.setForeground(new java.awt.Color(255, 51, 51));
        cmd_viewstockadded.setText("VIEW STOCK ADDED");
        cmd_viewstockadded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_viewstockaddedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36));
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "YOUR DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        role.setFont(new java.awt.Font("Tahoma", 1, 11));
        role.setForeground(new java.awt.Color(0, 204, 255));
        role.setText("worker");

        jLabel3.setText("role:");

        jLabel4.setText("branch:");

        branch.setFont(new java.awt.Font("Tahoma", 1, 11));
        branch.setForeground(new java.awt.Color(0, 204, 255));

        jLabel5.setText("userid:");

        user.setForeground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmd_maketransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_viewalltransactions))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(cmd_viewstockadded, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(cmd_addstock, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                        .addGap(59, 59, 59)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmd_addstock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmd_maketransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_viewalltransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_viewstockadded, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_addstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addstockActionPerformed
close();
addstock s=new addstock(this.jLabel2.getText(),this.role.getText(),this.branch.getText());
s.setVisible(true);

 this.addPropertyChangeListener((PropertyChangeListener) s);
          
    }//GEN-LAST:event_cmd_addstockActionPerformed

    private void cmd_maketransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_maketransactionActionPerformed
close();
        workertransconfirm b = new workertransconfirm(this.jLabel2.getText(),this.branch.getText());
        b.setVisible(true);
         this.addPropertyChangeListener((PropertyChangeListener) b);



    }//GEN-LAST:event_cmd_maketransactionActionPerformed

    private void cmd_viewalltransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_viewalltransactionsActionPerformed
close();
        alltransworker s=new alltransworker(this.jLabel2.getText(),this.branch.getText());
s.setVisible(true);
 this.addPropertyChangeListener((PropertyChangeListener) s);
          
    }//GEN-LAST:event_cmd_viewalltransactionsActionPerformed

    private void cmd_viewstockaddedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_viewstockaddedActionPerformed
close();
        viewstockadded s=new viewstockadded(this.jLabel2.getText(),this.branch.getText());
s.setVisible(true);
 this.addPropertyChangeListener((PropertyChangeListener) s);
    }//GEN-LAST:event_cmd_viewstockaddedActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       close();
        login s=new login();
       s.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new worker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel branch;
    private javax.swing.JButton cmd_addstock;
    private javax.swing.JButton cmd_maketransaction;
    private javax.swing.JButton cmd_viewalltransactions;
    private javax.swing.JButton cmd_viewstockadded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel role;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

}
